amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.1
    alpha3: 0.1
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: base_link
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9
    do_beamskip: false
    global_frame_id: map
    lambda: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0
    laser_min_range: 0.1
    laser_model_type: likelihood_field
    laser_z_hit: 0.95
    laser_z_max: 0.05
    laser_z_rand: 0.5
    laser_z_short: 0.05
    laser_sigma_hit: 0.2
    link_min_dist: 0.2
    link_max_dist: 2.0
    link_match_minimum_response_fine: 0.1
    odom_model_type: diff
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2
    odom_alpha5: 0.2
    initial_cov_xx: 0.25
    initial_cov_yy: 0.25
    initial_cov_aa: 0.0685
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    max_particles: 2000
    min_particles: 500
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    scan_topic: /scan
    map_topic: /map
    odom_topic: /odom
    transform_tolerance: 1.0
    update_min_d: 0.2
    update_min_a: 0.2
